services:
    init-volumes:
        image: busybox
        user: "0"
        command: >
            sh -c "mkdir -p .docker/redmine-dev_data/files .docker/redmine-dev_data/sqlite
            .docker/redmine-60100_data/files .docker/redmine-60100_data/sqlite
            .docker/redmine-60007_data/files .docker/redmine-60007_data/sqlite
            .docker/redmine-50110_data/files .docker/redmine-50110_data/sqlite &&
            chmod -R 777 .docker/redmine-*_data/"
        volumes:
            - ./:/work
        working_dir: /work

    php:
        build: # Info to build the Docker image
            context: ./.docker # Specify where the Dockerfile is located (e.g. in the root directory of the project)
            dockerfile: PHP74-Dockerfile # Specify the name of the Dockerfile
        ports:
            - 8111:80
        depends_on:
            - init-volumes
            - redmine-dev
        volumes:
            - ./:/var/www/project/ # Location of the project for php-fpm. Note this should be the same for NGINX.*

    redmine-dev:
        image: redmine:6.1.0
        user: "33:33"
        ports:
            - "3000:3000"
        environment:
            # Workaround: Remove secret for Rails 7.2 so it will be generated automatically
            # @see https://github.com/docker-library/redmine/issues/349#issuecomment-2516634932
            # REDMINE_SECRET_KEY_BASE: supersecretkey
            REDMINE_PLUGINS_MIGRATE: true
        volumes:
            - ./.docker/redmine-dev_data/files:/usr/src/redmine/files
            - ./.docker/redmine-dev_data/sqlite:/usr/src/redmine/sqlite

    behat:
        build: # PHP container for Behat tests (needs Redmine services)
            context: ./.docker # Specify where the Dockerfile is located (e.g. in the root directory of the project)
            dockerfile: Behat-Dockerfile # Specify the name of the Dockerfile
        depends_on:
            - init-volumes
            - redmine-6-1
            - redmine-6-0
            - redmine-5-1
        volumes:
            - ./:/var/www/project/ # Location of the project for php-fpm. Note this should be the same for NGINX.*

    # Make sure the following services are configured in:
    # - /tests/Behat/behat.yml

    redmine-6-1:
        image: redmine:6.1.0
        user: "33:33"
        ports:
            - "5061:3000"
        environment:
            # Workaround: Remove secret for Rails 7.2 so it will be generated automatically
            # @see https://github.com/docker-library/redmine/issues/349#issuecomment-2516634932
            # REDMINE_SECRET_KEY_BASE: supersecretkey
            REDMINE_PLUGINS_MIGRATE: true
        volumes:
            - ./.docker/redmine-60100_data/files:/usr/src/redmine/files
            - ./.docker/redmine-60100_data/sqlite:/usr/src/redmine/sqlite

    redmine-6-0:
        image: redmine:6.0.7
        user: "33:33"
        ports:
            - "5060:3000"
        environment:
            # Workaround: Remove secret for Rails 7.2 so it will be generated automatically
            # @see https://github.com/docker-library/redmine/issues/349#issuecomment-2516634932
            # REDMINE_SECRET_KEY_BASE: supersecretkey
            REDMINE_PLUGINS_MIGRATE: true
        volumes:
            - ./.docker/redmine-60007_data/files:/usr/src/redmine/files
            - ./.docker/redmine-60007_data/sqlite:/usr/src/redmine/sqlite

    redmine-5-1:
        image: redmine:5.1.10
        user: "33:33"
        ports:
            - "5051:3000"
        environment:
            REDMINE_SECRET_KEY_BASE: supersecretkey
            REDMINE_PLUGINS_MIGRATE: true
        volumes:
            - ./.docker/redmine-50110_data/files:/usr/src/redmine/files
            - ./.docker/redmine-50110_data/sqlite:/usr/src/redmine/sqlite
